# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/rest-clients.json
RestClients:
  langChain:
    UUID: 4fc2b880-8b39-4219-baa5-ada7f40ddb92
    Url: https://api.openai.com
    Properties:
      SensitiveData: 'true'
