# yaml-language-server: $schema=https://json-schema.axonivy.com/config/14.0.0/variables.json
Variables:
  AI:
    Providers:
      OpenAI:
        #[password]
        APIKey: ${decrypt:}
        BaseUrl: ""
        # The default model, if not explicitly specified on the calling Agent.
        #
        # See dev.langchain4j.model.openai.OpenAiChatModelName for the list of all supported models
        # [enum: gpt-4o, gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-5]
        DefaultModel: ""
